### ISSUE TITLE
Comma in amount sent to paypal produces an error

### ISSUE THREAD

**Issue by vendredi5h** [enupal/paypal#5]
### Description
**Issue**: When I click on the "Buy Now", Paypal shows an error page saying: "Things don't appear to be working at the moment. Please try again later."
**Cause**: The "amount" value has a comma as decimal separator and Paypal does not feel right about it. 
**Workaround**: Manually replacing the "," by a "." in chrome developer tools solves this issue.

**Correction**: replacing line 6 in button.twig solve this problem
from: 
    `<input name="amount" value="{{ button.amount | number }}" type="hidden">`
to:
    `<input name="amount" value="{{ button.amount | number_format(2, ".", "") }}" type="hidden">`

There's another issue related to this. When you edit a button, the amount previously entered with a a dot as a decimal separator is displayed with a comma separator, and when I save my new changes (unrelated to the amount), I get this error:
```
Database Exception – yii\db\Exception
SQLSTATE[HY000]: General error: 1366 Incorrect decimal value: '20,00' for column 'amount' at row 1
The SQL being executed was: UPDATE `enupalpaypal_buttons` SET `amount`='20,00', `dateUpdated`='2020-02-08 19:30:17' WHERE `id`=75
```

### Additional info

- Craft version: 3.4.5
- PHP version: 7.1.7
- Database driver & version: MySQL 8.0.18
- Plugin version: 1.1.0
- Windows Regional settings: fr_CA which has a comma as currency decimal separator

**Comment by andrelopez** [comment]
Hi @vendredi5h We just released Paypal Buttons v1.2.0 with a fix to this issue and also support to Craft 3.4 

Thanks for reporting!
